spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/minegocio}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: ${PORT:8080}
